version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Nvidia_geforce940mx
      MYSQL_DATABASE: shopdevgo
      MYSQL_USER: shovdev_user
      MYSQL_PASSWORD: Nvidia_geforce940mx
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "63379:6379"
    volumes:
      - redis_data:/data

  crm.shopdev.com:
    container_name: go_backend_crm_shopdev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8008:8000"

volumes:
  mysql_data:
  redis_data:
